app/routes.php
<?php
/**
 * CSRF Protection
 */
Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);
/** ------------------------------------------
 *  Route model binding
 *  ------------------------------------------
 */
Route::model('user', 'User');
Route::model('faq', 'Faq');
Route::model('plans', 'Plan');
Route::model('products', 'Product');
Route::model('subscriptions', 'Subscription');
/** ------------------------------------------
 *  Route constraint patterns
 *  ------------------------------------------
 */
Route::pattern('user', '[0-9]+');
Route::pattern('faq', '[0-9]+');
Route::pattern('plans', '[0-9]+');

Route::get('/', ['as' => 'home', function () {
//    $config      = [
//        'key'    => 'AKIAIHCU6246VXRMYRXA',
//        'secret' => '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',
//        'bucket' => 'gp-templates',
//        'prefix' => null,
//        'region' => 'ap-southeast-2',
//    ];
//    $aws         = \Aws\Common\Aws::factory($config);
//    $bucket      = 'gp-templates';
//    $fileName    = 'firstcategoryPzc9L1ksRvf9bkH1wgUs.jpg';
//    $client      = $aws->get('s3');
//    $downloadUrl = $client->getObjectUrl($bucket, '2015/03/firstcategoryPzc9L1ksRvf9bkH1wgUs.jpg', '+5 minutes', [
//        'ResponseContentDisposition' => 'attachment; filename="' . $fileName . '"',
//    ]);

    return Redirect::route('login');
}]);
/** ------------------------------------------
 *  Session Routes
 *  ------------------------------------------
 */
Route::get('login', ['as' => 'login', 'uses' => 'SessionController@create']);
Route::get('logout', ['as' => 'logout', 'uses' => 'SessionController@destroy']);
Route::resource('sessions', 'SessionController', ['only' => ['create', 'store', 'destroy']]);
/**
 * Registration / Activation / Forgot password
 */
Route::group(['before' => 'guest'], function () {
    Route::post('register', 'RegistrationController@store');
    Route::post('resend', 'RegistrationController@resend');
    Route::post('forgot', 'RegistrationController@forgot');
    Route::get('invitation', ['before' => 'invite', 'as' => 'user.invitation', 'uses' => 'RegistrationController@invitation']);
    Route::post('invitation/register', 'RegistrationController@registerInvitation');
    Route::get('users/{user}/activate/{code}', 'RegistrationController@activate');
    Route::get('users/{user}/reset/{code}', 'RegistrationController@reset');
});
/**
 *  User Routes
 */
Route::group(['before' => 'auth|standardUser'], function () {
    Route::post('first_login', 'UserProfileController@postFirstLogin');
});
Route::group(['before' => 'auth|standardUser|firstLogin'], function () {
    Route::get('dashboard', ['as' => 'user.dashboard', 'uses' => 'UserDashboardController@index']);
    /**
     * User Profile Routes
     */
    Route::get('profile', ['as' => 'user.profile', 'uses' => 'UserProfileController@index']);
    Route::post('profile/{user}/details', 'UserProfileController@updateDetails');
    Route::post('profile/{user}/password', 'UserProfileController@updatePassword');
    Route::post('profile/{user}/billing-address', 'UserProfileController@updateBillingAddress');
    Route::post('profile/{user}/church-details', 'UserProfileController@updateChurchDetails');
    /*
     * User Invitation Routes
     */
    Route::get('invite', ['as' => 'invite', 'uses' => 'UserInviteController@index']);
    Route::post('invite/send-invitation', 'UserInviteController@store');
    /*
     * User Faq Route
     */

    Route::resource('faq', 'UserFaqController', ['only' => 'index']);
    /*
     * plans subscription route
     */
    Route::get('my-plans', ['as' => 'user.my-plan', 'uses' => 'UserPlansController@getMyPlans']);
    Route::resource('plans', 'UserPlansController');
    Route::get('plans/{plans}/get-started', ['as' => 'user.plan.getStarted', 'uses' => 'UserPlansController@getStart']);
    Route::post('plans/{plans}/get-started', 'UserPlansController@postStart');
    Route::get('getpagination', 'UserPlansController@getPagination');
    Route::get('getpaginationproducts', 'UserPlansController@getPaginationProducts');
    Route::get('getpaginationaddons', 'UserPlansController@getAddons');
    /*
     * Subscription Route
     */
    Route::resource('subscriptions', 'UserSubscriptionController', ['only' => 'index']);
    Route::post('subscriptions/{subscriptions}/cancel',['as' => 'user.subscription.cancel', 'uses' =>'UserSubscriptionController@cancelSubscription']);
    Route::post('subscriptions/{subscriptions}/resume',['as' => 'user.subscription.resume', 'uses' =>'UserSubscriptionController@resumeSubscription']);
    /*
     * Cards Route
     */
    Route::resource('cards', 'UserCardsController');

});
Route::get('form', ['as' => 'site.formwizard.index', 'uses' => 'HomeController@index']);
Route::get('products', ['as' => 'users.products.index', 'uses' => 'UserProductController@index']);
/**
 * Admin Routes
 */
Route::group(['prefix' => 'admin', 'before' => 'auth|admin'], function () {
    Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'AdminDashboardController@index']);
    /*
     * User Route
     */
    Route::resource('users', 'AdminUserController', ['except' => 'destroy']);
    Route::get('users/delete/{user}', ['as' => 'admin.users.delete', 'uses' => 'AdminUserController@getDelete']);
    Route::get('users/activate/{user}', ['as' => 'admin.users.activate', 'uses' => 'AdminUserController@getActivate']);

    /*
     * Category Routes
     */
    Route::get('categories/detail/{id}', ['as' => 'admin.categories.details', 'uses' => 'AdminCategoryController@getDetail']);
    Route::get('categories/delete/{id}', ['as' => 'admin.categories.delete', 'uses' => 'AdminCategoryController@getDelete']);
    Route::resource('categories', 'AdminCategoryController', ['except' => 'create', 'delete']);
    /*
     * Product Routes
     */
    Route::get('products/delete/{id}', ['as' => 'admin.products.delete', 'uses' => 'AdminProductController@getDelete']);
    Route::resource('products', 'AdminProductController', ['except' => 'destroy']);
    /*
     * FAQ Route
     */
    Route::resource('faq', 'AdminFaqController', ['except' => ['create', 'delete']]);

    /*
     * Plans and Add-ons Route
     */
    Route::resource('plans', 'AdminPlanController', ['except' => 'destroy']);
    Route::resource('plans.addons', 'AdminAddonController', ['only' => ['index', 'store']]);
    Route::get('/plans/{plans}/addons/{products}/delete', ['as' => 'admin.plans.addons.delete', 'uses' => 'AdminAddonController@delete']);
});

app/models/Faq.php
<?php

class Faq extends \Eloquent {
    protected $fillable = ['title', 'answer'];
    protected $table = 'faq';
}

app/views/admin/faq/edit.blade.php
@extends('admin.layouts.master_admin')
@section('content')
<div id="page-content">
    <!-- FAQ Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-info"></i>Frequently Asked Questions<br><small>Answers for all your users’ questions!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>Pages</li>
        <li><a href="">FAQ</a></li>
    </ul>
    <!-- END FAQ Header -->
    <!-- FAQ Block -->
    <div class="block block-alt-noborder">
        @include('admin.layouts.notification')
        <!-- FAQ Content -->
        <div class="row">
            <div class="col-md-6 col-lg-6" id="new_faq_block">
                <div class="block">
                    <div class="block-title">
                        <h2><i class="fa fa-pencil"></i> <strong>Edit</strong> FAQ</h2>
                    </div>
                    {{ Form::model($faq,['route' => ['admin.faq.update',$faq->id], 'method' => 'PUT', 'role' => 'form', 'class' => 'form-horizontal form-bordered']) }}
                    {{ Form::hidden('id') }}
                        <!-- Title Form Input -->
                        <div class="form-group">
                            {{ Form::label('title', 'Title ', ['class' => 'col-xs-3 control-label ']) }}
                            <div class="col-xs-9 ">
                                {{ Form::text('title', Input::old('title'), ['class' => 'form-control', 'placeholder' => 'Enter Title Here .. ', 'required']) }}
                            </div>
                        </div>
                        <!-- Answer Form Input -->
                        <div class="form-group">
                            {{ Form::label('answer', 'Answer ', ['class' => 'col-md-3 control-label ']) }}
                            <div class="col-md-9 ">
                                {{ Form::textarea('long_description', $faq->answer, ['class' => 'ckeditor' ,'placeholder' =>'aaa']) }}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-9 col-xs-offset-3">
                                {{ Form::submit('Save FAQ' , ['class' => 'btn btn-sm btn-primary']) }}
                            </div>
                        </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('scripts')
    <script src="/proui/js/helpers/ckeditor/ckeditor.js"></script>
@stop

app/views/admin/faq/index.blade.php
@extends('admin.layouts.master_admin')
@section('content')
<div id="page-content">
    <!-- FAQ Header -->
    <div class="content-header">
        <div class="header-section">
            <h1>
                <i class="fa fa-info"></i>Frequently Asked Questions<br><small>Answers for all your users’ questions!</small>
            </h1>
        </div>
    </div>
    <ul class="breadcrumb breadcrumb-top">
        <li>Pages</li>
        <li><a href="">FAQ</a></li>
    </ul>
    <!-- END FAQ Header -->
    <!-- FAQ Block -->
    <div class="block block-alt-noborder">
        <!-- FAQ Content -->
        <div class="row">
            <div class="col-md-6 col-lg-6">
                @foreach($faqs as $faq)
                <div id="faq{{$faq->id}}" class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><i class="fa fa-angle-right"></i>
                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#faq{{$faq->id}}" href="#faq{{$faq->id}}_q{{$faq->id}}">
                                    {{ $faq->title }}
                                    <div class="pull-right">
                                        <a href="{{ route('admin.faq.edit',[$faq->id]) }}" class=" "><i class="fa fa-pencil"></i></a>
                                    </div>
                                </a>
                            </h4>
                        </div>
                        <div id="faq{{$faq->id}}_q{{$faq->id}}" class="panel-collapse collapse in">
                            <div class="panel-body">
                                {{ $faq->answer }}
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>

            <div class="col-md-6 col-lg-6" id="new_faq_block">
                <div class="block">
                    <div class="block-title">
                        <h2><i class="fa fa-pencil"></i> <strong>New</strong> FAQ</h2>
                    </div>
                    {{ Form::open(['action' => 'AdminFaqController@store', 'role' => 'form', 'class' => 'form-horizontal form-bordered']) }}
                        <!-- Title Form Input -->
                        <div class="form-group">
                            {{ Form::label('title', 'Title ', ['class' => 'col-xs-3 control-label ']) }}
                            <div class="col-xs-9 ">
                                {{ Form::text('title', Input::old('title'), ['class' => 'form-control', 'placeholder' => 'Enter Title Here .. ', 'required']) }}
                            </div>
                        </div>

                        <!-- Answer Form Input -->
                        <div class="form-group">
                            {{ Form::label('answer', 'Answer ', ['class' => 'col-md-3 control-label ']) }}
                            <div class="col-md-9 ">
                                <textarea id="answer" name="answer" class="ckeditor"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-9 col-xs-offset-3">
                                {{ Form::submit('Save FAQ' , ['class' => 'btn btn-sm btn-primary']) }}
                            </div>
                        </div>

                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('scripts')
    <script src="/proui/js/helpers/ckeditor/ckeditor.js"></script>
@stop