app/routes.php
<?php
/**
 * CSRF Protection
 */
Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);
/** ------------------------------------------
 *  Route model binding
 *  ------------------------------------------
 */
Route::model('user', 'User');
Route::model('faq', 'Faq');
Route::model('plans', 'Plan');
Route::model('products', 'Product');
Route::model('subscriptions', 'Subscription');
/** ------------------------------------------
 *  Route constraint patterns
 *  ------------------------------------------
 */
Route::pattern('user', '[0-9]+');
Route::pattern('faq', '[0-9]+');
Route::pattern('plans', '[0-9]+');

Route::get('/', ['as' => 'home', function () {
//    $config      = [
//        'key'    => 'AKIAIHCU6246VXRMYRXA',
//        'secret' => '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',
//        'bucket' => 'gp-templates',
//        'prefix' => null,
//        'region' => 'ap-southeast-2',
//    ];
//    $aws         = \Aws\Common\Aws::factory($config);
//    $bucket      = 'gp-templates';
//    $fileName    = 'firstcategoryPzc9L1ksRvf9bkH1wgUs.jpg';
//    $client      = $aws->get('s3');
//    $downloadUrl = $client->getObjectUrl($bucket, '2015/03/firstcategoryPzc9L1ksRvf9bkH1wgUs.jpg', '+5 minutes', [
//        'ResponseContentDisposition' => 'attachment; filename="' . $fileName . '"',
//    ]);

    return Redirect::route('login');
}]);
/** ------------------------------------------
 *  Session Routes
 *  ------------------------------------------
 */
Route::get('login', ['as' => 'login', 'uses' => 'SessionController@create']);
Route::get('logout', ['as' => 'logout', 'uses' => 'SessionController@destroy']);
Route::resource('sessions', 'SessionController', ['only' => ['create', 'store', 'destroy']]);
/**
 * Registration / Activation / Forgot password
 */
Route::group(['before' => 'guest'], function () {
    Route::post('register', 'RegistrationController@store');
    Route::post('resend', 'RegistrationController@resend');
    Route::post('forgot', 'RegistrationController@forgot');
    Route::get('invitation', ['before' => 'invite', 'as' => 'user.invitation', 'uses' => 'RegistrationController@invitation']);
    Route::post('invitation/register', 'RegistrationController@registerInvitation');
    Route::get('users/{user}/activate/{code}', 'RegistrationController@activate');
    Route::get('users/{user}/reset/{code}', 'RegistrationController@reset');
});
/**
 *  User Routes
 */
Route::group(['before' => 'auth|standardUser'], function () {
    Route::post('first_login', 'UserProfileController@postFirstLogin');
});
Route::group(['before' => 'auth|standardUser|firstLogin'], function () {
    Route::get('dashboard', ['as' => 'user.dashboard', 'uses' => 'UserDashboardController@index']);
    /**
     * User Profile Routes
     */
    Route::get('profile', ['as' => 'user.profile', 'uses' => 'UserProfileController@index']);
    Route::post('profile/{user}/details', 'UserProfileController@updateDetails');
    Route::post('profile/{user}/password', 'UserProfileController@updatePassword');
    Route::post('profile/{user}/billing-address', 'UserProfileController@updateBillingAddress');
    Route::post('profile/{user}/church-details', 'UserProfileController@updateChurchDetails');
    /*
     * User Invitation Routes
     */
    Route::get('invite', ['as' => 'invite', 'uses' => 'UserInviteController@index']);
    Route::post('invite/send-invitation', 'UserInviteController@store');
    /*
     * User Faq Route
     */

    Route::resource('faq', 'UserFaqController', ['only' => 'index']);
    /*
     * plans subscription route
     */
    Route::get('my-plans', ['as' => 'user.my-plan', 'uses' => 'UserPlansController@getMyPlans']);
    Route::resource('plans', 'UserPlansController');
    Route::get('plans/{plans}/get-started', ['as' => 'user.plan.getStarted', 'uses' => 'UserPlansController@getStart']);
    Route::post('plans/{plans}/get-started', 'UserPlansController@postStart');
    Route::get('getpagination', 'UserPlansController@getPagination');
    Route::get('getpaginationproducts', 'UserPlansController@getPaginationProducts');
    Route::get('getpaginationaddons', 'UserPlansController@getAddons');
    /*
     * Subscription Route
     */
    Route::resource('subscriptions', 'UserSubscriptionController', ['only' => 'index']);
    Route::post('subscriptions/{subscriptions}/cancel',['as' => 'user.subscription.cancel', 'uses' =>'UserSubscriptionController@cancelSubscription']);
    Route::post('subscriptions/{subscriptions}/resume',['as' => 'user.subscription.resume', 'uses' =>'UserSubscriptionController@resumeSubscription']);
    /*
     * Cards Route
     */
    Route::resource('cards', 'UserCardsController');

});
Route::get('form', ['as' => 'site.formwizard.index', 'uses' => 'HomeController@index']);
Route::get('products', ['as' => 'users.products.index', 'uses' => 'UserProductController@index']);
/**
 * Admin Routes
 */
Route::group(['prefix' => 'admin', 'before' => 'auth|admin'], function () {
    Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'AdminDashboardController@index']);
    /*
     * User Route
     */
    Route::resource('users', 'AdminUserController', ['except' => 'destroy']);
    Route::get('users/delete/{user}', ['as' => 'admin.users.delete', 'uses' => 'AdminUserController@getDelete']);
    Route::get('users/activate/{user}', ['as' => 'admin.users.activate', 'uses' => 'AdminUserController@getActivate']);

    /*
     * Category Routes
     */
    Route::get('categories/detail/{id}', ['as' => 'admin.categories.details', 'uses' => 'AdminCategoryController@getDetail']);
    Route::get('categories/delete/{id}', ['as' => 'admin.categories.delete', 'uses' => 'AdminCategoryController@getDelete']);
    Route::resource('categories', 'AdminCategoryController', ['except' => 'create', 'delete']);
    /*
     * Product Routes
     */
    Route::get('products/delete/{id}', ['as' => 'admin.products.delete', 'uses' => 'AdminProductController@getDelete']);
    Route::resource('products', 'AdminProductController', ['except' => 'destroy']);
    /*
     * FAQ Route
     */
    Route::resource('faq', 'AdminFaqController', ['except' => ['create', 'delete']]);

    /*
     * Plans and Add-ons Route
     */
    Route::resource('plans', 'AdminPlanController', ['except' => 'destroy']);
    Route::resource('plans.addons', 'AdminAddonController', ['only' => ['index', 'store']]);
    Route::get('/plans/{plans}/addons/{products}/delete', ['as' => 'admin.plans.addons.delete', 'uses' => 'AdminAddonController@delete']);
});

app/views/admin/layouts/_partials/alt_sidebar.blade.php
<div id="sidebar-alt">
    <!-- Wrapper for scrolling functionality -->
    <div id="sidebar-alt-scroll">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
            <!-- Chat -->
            <!-- Chat demo functionality initialized in js/app.js -> chatUi() -->
            <a href="page_ready_chat.html" class="sidebar-title">
                <i class="gi gi-comments pull-right"></i> <strong>Chat</strong>UI
            </a>
            <!-- Chat Users -->
            <ul class="chat-users clearfix">
                <li>
                    <a href="javascript:void(0)" class="chat-user-online">
                        <span></span>
                        {{--<img src="img/placeholders/avatars/avatar12.jpg" alt="avatar" class="img-circle">--}}
                    </a>
                </li>
            </ul>
            <!-- END Chat Users -->

            <!-- Chat Talk -->
            <div class="chat-talk display-none">
                <!-- Chat Info -->
                <div class="chat-talk-info sidebar-section">
                    <button id="chat-talk-close-btn" class="btn btn-xs btn-default pull-right">
                        <i class="fa fa-times"></i>
                    </button>
                    {{--<img src="img/placeholders/avatars/avatar5.jpg" alt="avatar" class="img-circle pull-left">--}}
                    <strong>John</strong> Doe
                </div>
                <!-- END Chat Info -->

                <!-- Chat Messages -->
                <ul class="chat-talk-messages">
                    <li class="text-center"><small>Yesterday, 18:35</small></li>
                    <li class="chat-talk-msg animation-slideRight">Hey admin?</li>
                    <li class="chat-talk-msg animation-slideRight">How are you?</li>
                    <li class="text-center"><small>Today, 7:10</small></li>
                    <li class="chat-talk-msg chat-talk-msg-highlight themed-border animation-slideLeft">I'm fine, thanks!</li>
                </ul>
                <!-- END Chat Messages -->

                <!-- Chat Input -->
                <form action="{{ URL::to('/') }}" method="post" id="sidebar-chat-form" class="chat-form">
                    <input type="text" id="sidebar-chat-message" name="sidebar-chat-message" class="form-control form-control-borderless" placeholder="Type a message..">
                </form>
                <!-- END Chat Input -->
            </div>
            <!--  END Chat Talk -->
            <!-- END Chat -->

            <!-- Activity -->
            <a href="javascript:void(0)" class="sidebar-title">
                <i class="fa fa-globe pull-right"></i> <strong>Activity</strong>UI
            </a>
            <div class="sidebar-section">
                <div class="alert alert-danger alert-alt">
                    <small>just now</small><br>
                    <i class="fa fa-thumbs-up fa-fw"></i> Upgraded to Pro plan
                </div>
                <div class="alert alert-info alert-alt">
                    <small>2 hours ago</small><br>
                    <i class="gi gi-coins fa-fw"></i> You had a new sale!
                </div>
                <div class="alert alert-success alert-alt">
                    <small>3 hours ago</small><br>
                    <i class="fa fa-plus fa-fw"></i> <a href="page_ready_user_profile.html"><strong>John Doe</strong></a> would like to become friends!<br>
                    <a href="javascript:void(0)" class="btn btn-xs btn-primary"><i class="fa fa-check"></i> Accept</a>
                    <a href="javascript:void(0)" class="btn btn-xs btn-default"><i class="fa fa-times"></i> Ignore</a>
                </div>
                <div class="alert alert-warning alert-alt">
                    <small>2 days ago</small><br>
                    Running low on space<br><strong>18GB in use</strong> 2GB left<br>
                    <a href="page_ready_pricing_tables.html" class="btn btn-xs btn-primary"><i class="fa fa-arrow-up"></i> Upgrade Plan</a>
                </div>
            </div>
            <!-- END Activity -->

            <!-- Messages -->
            <a href="page_ready_inbox.html" class="sidebar-title">
                <i class="fa fa-envelope pull-right"></i> <strong>Messages</strong>UI (5)
            </a>
            <div class="sidebar-section">
                <div class="alert alert-alt">
                    Debra Stanley<small class="pull-right">just now</small><br>
                    <a href="page_ready_inbox_message.html"><strong>New Follower</strong></a>
                </div>
            </div>
            <!-- END Messages -->
        </div>
        <!-- END Sidebar Content -->
    </div>
    <!-- END Wrapper for scrolling functionality -->
</div>

app/views/admin/layouts/_partials/confirm_modal.blade.php
<div id="confirm-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Confirm delete?</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No, no!</button>
                <a href="#" id="confirm-delete" class="btn btn-danger">Yes, delete</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

app/views/admin/layouts/_partials/dashboard_header.blade.php
<div class="content-header">
    <ul class="nav-horizontal text-center">
        <li {{ Request::is('admin') ? ' class="active"' : null }}>
            <a href="{{ URL::to('admin.dashboard') }}"><i class="fa fa-home"></i> Dashboard</a>
        </li>

        <li {{ Request::is('admin/users*') ? ' class="active"' : null }}>
            <a href="{{ URL::to('admin/users') }}"><i class="fa fa-users"></i> Users</a>
        </li>

        <li {{ Request::is('admin/products*') ? ' class="active"' : null }}>
            <a href="{{ URL::to('admin/products') }}"><i class="fa fa-cubes"></i> Products</a>
        </li>
        <li> <a href="javascript:void(0)"><i class="fa fa-bar-chart"></i> Statistics</a> </li>

        <li {{ Request::is('admin/faq*') ? ' class="active"' : null }}>
            <a href="{{ URL::to('admin/faq') }}"><i class="fa fa-question"></i> FAQ</a>
        </li>
        <li> <a href="javascript:void(0)"><i class="fa fa-link"></i> Referrals</a> </li>
        <li> <a href="javascript:void(0)"><i class="fa fa-dollar"></i> Billings</a> </li>
    </ul>
</div>

app/views/admin/layouts/_partials/footer.blade.php
<a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>

<!-- User Settings, modal -->

<!-- END User Settings -->

<!-- Remember to include excanvas for IE8 chart support -->
<!--[if IE 8]><script src="/proui/js/helpers/excanvas.min.js"></script><![endif]-->

<!-- Include Jquery library from Google's CDN but if something goes wrong get Jquery from local file (Remove 'http:' if you have SSL) -->
<script src="/proui/js/vendor/jquery-1.11.2.min.js"></script>
<script>!window.jQuery && document.write(decodeURI('%3Cscript src="/proui/js/vendor/jquery-1.11.1.min.js"%3E%3C/script%3E'));</script>

<!-- Bootstrap.js, Jquery plugins and Custom JS code -->
<script src="/proui/js/vendor/bootstrap.min.js"></script>
<script src="/proui/js/plugins.js"></script>
<script src="/proui/js/app.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

<script>
    !function ($) {
        $(function(){
            $(document).on('click', '.btn-confirm', function(e) {
                e.preventDefault();
                $delete_url = $(this).attr('href');
                $('#confirm-delete').attr('href', $delete_url);
                $('#confirm-modal').modal('show');
            });
            var currentLocation = $("#navbar-menu-dropdown ul.dropdown-menu li.active a").html();
            $("#navbar-menu-current-text").html(currentLocation);
        })
    }(window.jQuery);
</script>
@yield('scripts')
</body>
</html>

app/views/admin/layouts/_partials/header.blade.php
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>{{ Config::get('site.name') }} :: @section('title')</title>

    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="robots" content="noindex, nofollow">

    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

    <!-- Icons -->
    <link rel="shortcut icon" href="/proui/img/favicon.png">
    <link rel="apple-touch-icon" href="/proui/img/icon57.png" sizes="57x57">
    <link rel="apple-touch-icon" href="/proui/img/icon72.png" sizes="72x72">
    <link rel="apple-touch-icon" href="/proui/img/icon76.png" sizes="76x76">
    <link rel="apple-touch-icon" href="/proui/img/icon114.png" sizes="114x114">
    <link rel="apple-touch-icon" href="/proui/img/icon120.png" sizes="120x120">
    <link rel="apple-touch-icon" href="/proui/img/icon144.png" sizes="144x144">
    <link rel="apple-touch-icon" href="/proui/img/icon152.png" sizes="152x152">
    <link rel="apple-touch-icon" href="/proui/img/icon180.png" sizes="180x180">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="/proui/css/bootstrap.min.css">
    <link rel="stylesheet" href="/proui/css/plugins.css">
    <link rel="stylesheet" href="/proui/css/main.css">
    <link rel="stylesheet" href="/proui/css/themes.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">

    @yield('styles')

    <script src="/proui/js/vendor/modernizr-respond.min.js"></script>
</head>
<body>

app/views/admin/layouts/_partials/main_sidebar.blade.php
<div id="sidebar">
  <div id="sidebar-scroll">
    <div class="sidebar-content">
      <a href="{{ URL::to('/') }}" class="sidebar-brand">
        <i class="gi gi-flash"></i>
        <span class="sidebar-nav-mini-hide">{{ Config::get('site.name')  }}</span>
      </a>
      <div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
        <div class="sidebar-user-avatar">
          <a href="#">
            {{ HTML::image('proui/img/placeholders/avatars/avatar1.jpg','avatar',['class' => 'widget-image img-circle pull-left animation-fadeIn']) }}
          </a>
        </div>
        <div class="sidebar-user-name"></div>
        <div class="sidebar-user-links">
          <a href="#" data-toggle="tooltip" data-placement="bottom" title="Profile"><i class="gi gi-user"></i></a>
          <a href="#modal-user-settings" data-toggle="modal" class="enable-tooltip" data-placement="bottom" title="Settings"><i class="gi gi-cogwheel"></i></a>
          <a href="{{ URL::to('logout') }}" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="gi gi-exit"></i></a>
        </div>
      </div>
      {{-- @include('admin.layouts._partials.theme_color') --}}
      <ul class="sidebar-nav">
        <li {{ Request::is('admin') ? ' class="active"' : null }}>
          <a href="{{ URL::to('admin') }}"><i class="gi gi-stopwatch sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Dashboard</span></a>
        </li>
        <li {{ Request::is('admin/users*') ? ' class="active"' : null }}>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-users sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Users</span></a>
          <ul>
            <li> <a href="{{ URL::route('admin.users.index') }}">All Users</a> </li>
            <li> <a href="{{ URL::route('admin.users.create') }}">New User</a> </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-cubes sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Products & Plans</span></a>
          <ul>
            <li> <a href="{{ URL::route('admin.categories.index') }}">Category</a> </li>
            <li> <a href="{{ URL::to('admin/products') }}">Products</a> </li>
            <li> <a href="{{ URL::to('admin/plans') }}">Plans</a> </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-bar-chart sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Statistics</span></a>
          <ul>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-question sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">FAQ's</span></a>
          <ul>
            <li> <a href="{{ URL::route('admin.faq.index') }}">All Faq</a> </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-link sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Referrals</span></a>
          <ul>
            <li> <a href="">Dashboard</a> </li>
          </ul>
        </li>
        <li>
          <a href="#" class="sidebar-nav-menu"><i class="fa fa-angle-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="fa fa-dollar sidebar-nav-icon"></i> <span class="sidebar-nav-mini-hide">Billings</span></a>
          <ul>
            <li> <a href="">Dashboard</a> </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <!-- END Wrapper for scrolling functionality -->
</div>

app/views/admin/layouts/_partials/preloader.blade.php
<div class="preloader themed-background">
    <h1 class="push-top-bottom text-light text-center"><strong>{{ Config::get('site.name') }}</strong></h1>
    <div class="inner">
        <h3 class="text-light visible-lt-ie9 visible-lt-ie10"><strong>Loading..</strong></h3>
        <div class="preloader-spinner hidden-lt-ie9 hidden-lt-ie10"></div>
    </div>
</div>

app/views/admin/layouts/_partials/setting_modal.blade.php
<div id="modal-user-settings" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header text-center">
                <h2 class="modal-title"><i class="fa fa-pencil"></i> Settings</h2>
            </div>
            <!-- END Modal Header -->

            <!-- Modal Body -->
            <div class="modal-body">
                <form action="index.html" method="post" enctype="multipart/form-data" class="form-horizontal form-bordered" onsubmit="return false;">
                    <fieldset>
                        <legend>Vital Info</legend>
                        <div class="form-group">
                            <label class="col-md-4 control-label">Username</label>
                            <div class="col-md-8">
                                <p class="form-control-static">Admin</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="user-settings-email">Email</label>
                            <div class="col-md-8">
                                <input type="email" id="user-settings-email" name="user-settings-email" class="form-control" value="admin@example.com">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="user-settings-notifications">Email Notifications</label>
                            <div class="col-md-8">
                                <label class="switch switch-primary">
                                    <input type="checkbox" id="user-settings-notifications" name="user-settings-notifications" value="1" checked>
                                    <span></span>
                                </label>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>Password Update</legend>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="user-settings-password">New Password</label>
                            <div class="col-md-8">
                                <input type="password" id="user-settings-password" name="user-settings-password" class="form-control" placeholder="Please choose a complex one..">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="user-settings-repassword">Confirm New Password</label>
                            <div class="col-md-8">
                                <input type="password" id="user-settings-repassword" name="user-settings-repassword" class="form-control" placeholder="..and confirm it!">
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group form-actions">
                        <div class="col-xs-12 text-right">
                            <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-sm btn-primary">Save Changes</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- END Modal Body -->
        </div>
    </div>
</div>

app/views/admin/layouts/_partials/theme_color.blade.php
<ul class="sidebar-section sidebar-themes clearfix sidebar-nav-mini-hide">
                <li> <a href="javascript:void(0)" class="themed-background-dark-night themed-border-night" data-theme="css/themes/night.css" data-toggle="tooltip" title="Night"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-amethyst themed-border-amethyst" data-theme="css/themes/amethyst.css" data-toggle="tooltip" title="Amethyst"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-modern themed-border-modern" data-theme="css/themes/modern.css" data-toggle="tooltip" title="Modern"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-autumn themed-border-autumn" data-theme="css/themes/autumn.css" data-toggle="tooltip" title="Autumn"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-flatie themed-border-flatie" data-theme="css/themes/flatie.css" data-toggle="tooltip" title="Flatie"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-spring themed-border-spring" data-theme="css/themes/spring.css" data-toggle="tooltip" title="Spring"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-fancy themed-border-fancy" data-theme="css/themes/fancy.css" data-toggle="tooltip" title="Fancy"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-fire themed-border-fire" data-theme="css/themes/fire.css" data-toggle="tooltip" title="Fire"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-coral themed-border-coral" data-theme="css/themes/coral.css" data-toggle="tooltip" title="Coral"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-lake themed-border-lake" data-theme="css/themes/lake.css" data-toggle="tooltip" title="Lake"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-forest themed-border-forest" data-theme="css/themes/forest.css" data-toggle="tooltip" title="Forest"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-waterlily themed-border-waterlily" data-theme="css/themes/waterlily.css" data-toggle="tooltip" title="Waterlily"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-emerald themed-border-emerald" data-theme="css/themes/emerald.css" data-toggle="tooltip" title="Emerald"></a> </li>
                <li> <a href="javascript:void(0)" class="themed-background-dark-blackberry themed-border-blackberry" data-theme="css/themes/blackberry.css" data-toggle="tooltip" title="Blackberry"></a> </li>
            </ul>