app/routes.php
<?php
/**
 * CSRF Protection
 */
Route::when('*', 'csrf', ['POST', 'PUT', 'PATCH', 'DELETE']);
/** ------------------------------------------
 *  Route model binding
 *  ------------------------------------------
 */
Route::model('user', 'User');
Route::model('faq', 'Faq');
Route::model('plans', 'Plan');
Route::model('products', 'Product');
Route::model('subscriptions', 'Subscription');
/** ------------------------------------------
 *  Route constraint patterns
 *  ------------------------------------------
 */
Route::pattern('user', '[0-9]+');
Route::pattern('faq', '[0-9]+');
Route::pattern('plans', '[0-9]+');

Route::get('/', ['as' => 'home', function () {
//    $config      = [
//        'key'    => 'AKIAIHCU6246VXRMYRXA',
//        'secret' => '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',
//        'bucket' => 'gp-templates',
//        'prefix' => null,
//        'region' => 'ap-southeast-2',
//    ];
//    $aws         = \Aws\Common\Aws::factory($config);
//    $bucket      = 'gp-templates';
//    $fileName    = 'firstcategoryPzc9L1ksRvf9bkH1wgUs.jpg';
//    $client      = $aws->get('s3');
//    $downloadUrl = $client->getObjectUrl($bucket, '2015/03/firstcategoryPzc9L1ksRvf9bkH1wgUs.jpg', '+5 minutes', [
//        'ResponseContentDisposition' => 'attachment; filename="' . $fileName . '"',
//    ]);

    return Redirect::route('login');
}]);
/** ------------------------------------------
 *  Session Routes
 *  ------------------------------------------
 */
Route::get('login', ['as' => 'login', 'uses' => 'SessionController@create']);
Route::get('logout', ['as' => 'logout', 'uses' => 'SessionController@destroy']);
Route::resource('sessions', 'SessionController', ['only' => ['create', 'store', 'destroy']]);
/**
 * Registration / Activation / Forgot password
 */
Route::group(['before' => 'guest'], function () {
    Route::post('register', 'RegistrationController@store');
    Route::post('resend', 'RegistrationController@resend');
    Route::post('forgot', 'RegistrationController@forgot');
    Route::get('invitation', ['before' => 'invite', 'as' => 'user.invitation', 'uses' => 'RegistrationController@invitation']);
    Route::post('invitation/register', 'RegistrationController@registerInvitation');
    Route::get('users/{user}/activate/{code}', 'RegistrationController@activate');
    Route::get('users/{user}/reset/{code}', 'RegistrationController@reset');
});
/**
 *  User Routes
 */
Route::group(['before' => 'auth|standardUser'], function () {
    Route::post('first_login', 'UserProfileController@postFirstLogin');
});
Route::group(['before' => 'auth|standardUser|firstLogin'], function () {
    Route::get('dashboard', ['as' => 'user.dashboard', 'uses' => 'UserDashboardController@index']);
    /**
     * User Profile Routes
     */
    Route::get('profile', ['as' => 'user.profile', 'uses' => 'UserProfileController@index']);
    Route::post('profile/{user}/details', 'UserProfileController@updateDetails');
    Route::post('profile/{user}/password', 'UserProfileController@updatePassword');
    Route::post('profile/{user}/billing-address', 'UserProfileController@updateBillingAddress');
    Route::post('profile/{user}/church-details', 'UserProfileController@updateChurchDetails');
    /*
     * User Invitation Routes
     */
    Route::get('invite', ['as' => 'invite', 'uses' => 'UserInviteController@index']);
    Route::post('invite/send-invitation', 'UserInviteController@store');
    /*
     * User Faq Route
     */

    Route::resource('faq', 'UserFaqController', ['only' => 'index']);
    /*
     * plans subscription route
     */
    Route::get('my-plans', ['as' => 'user.my-plan', 'uses' => 'UserPlansController@getMyPlans']);
    Route::resource('plans', 'UserPlansController');
    Route::get('plans/{plans}/get-started', ['as' => 'user.plan.getStarted', 'uses' => 'UserPlansController@getStart']);
    Route::post('plans/{plans}/get-started', 'UserPlansController@postStart');
    Route::get('getpagination', 'UserPlansController@getPagination');
    Route::get('getpaginationproducts', 'UserPlansController@getPaginationProducts');
    Route::get('getpaginationaddons', 'UserPlansController@getAddons');
    /*
     * Subscription Route
     */
    Route::resource('subscriptions', 'UserSubscriptionController', ['only' => 'index']);
    Route::post('subscriptions/{subscriptions}/cancel',['as' => 'user.subscription.cancel', 'uses' =>'UserSubscriptionController@cancelSubscription']);
    Route::post('subscriptions/{subscriptions}/resume',['as' => 'user.subscription.resume', 'uses' =>'UserSubscriptionController@resumeSubscription']);
    /*
     * Cards Route
     */
    Route::resource('cards', 'UserCardsController');

});
Route::get('form', ['as' => 'site.formwizard.index', 'uses' => 'HomeController@index']);
Route::get('products', ['as' => 'users.products.index', 'uses' => 'UserProductController@index']);
/**
 * Admin Routes
 */
Route::group(['prefix' => 'admin', 'before' => 'auth|admin'], function () {
    Route::get('/', ['as' => 'admin.dashboard', 'uses' => 'AdminDashboardController@index']);
    /*
     * User Route
     */
    Route::resource('users', 'AdminUserController', ['except' => 'destroy']);
    Route::get('users/delete/{user}', ['as' => 'admin.users.delete', 'uses' => 'AdminUserController@getDelete']);
    Route::get('users/activate/{user}', ['as' => 'admin.users.activate', 'uses' => 'AdminUserController@getActivate']);

    /*
     * Category Routes
     */
    Route::get('categories/detail/{id}', ['as' => 'admin.categories.details', 'uses' => 'AdminCategoryController@getDetail']);
    Route::get('categories/delete/{id}', ['as' => 'admin.categories.delete', 'uses' => 'AdminCategoryController@getDelete']);
    Route::resource('categories', 'AdminCategoryController', ['except' => 'create', 'delete']);
    /*
     * Product Routes
     */
    Route::get('products/delete/{id}', ['as' => 'admin.products.delete', 'uses' => 'AdminProductController@getDelete']);
    Route::resource('products', 'AdminProductController', ['except' => 'destroy']);
    /*
     * FAQ Route
     */
    Route::resource('faq', 'AdminFaqController', ['except' => ['create', 'delete']]);

    /*
     * Plans and Add-ons Route
     */
    Route::resource('plans', 'AdminPlanController', ['except' => 'destroy']);
    Route::resource('plans.addons', 'AdminAddonController', ['only' => ['index', 'store']]);
    Route::get('/plans/{plans}/addons/{products}/delete', ['as' => 'admin.plans.addons.delete', 'uses' => 'AdminAddonController@delete']);
});

app/controllers/UserController.php
<?php

use Gospel\Repo\User\UserInterface;
use Gospel\Repo\Group\GroupInterface;
use Gospel\Service\Form\Register\RegisterForm;
use Gospel\Service\Form\User\UserForm;
use Gospel\Service\Form\ResendActivation\ResendActivationForm;
use Gospel\Service\Form\ForgotPassword\ForgotPasswordForm;
use Gospel\Service\Form\ChangePassword\ChangePasswordForm;
use Gospel\Service\Form\SuspendUser\SuspendUserForm;
use Gospel\customer_io\CustomerIO;

class UserController extends BaseController
{

    protected $user;
    protected $group;
    protected $registerForm;
    protected $userForm;
    protected $resendActivationForm;
    protected $forgotPasswordForm;
    protected $changePasswordForm;
    protected $suspendUserForm;

    /**
     * Instantiate a new UserController
     * @param UserInterface $user
     * @param GroupInterface $group
     * @param RegisterForm $registerForm
     * @param UserForm $userForm
     * @param ResendActivationForm $resendActivationForm
     * @param ForgotPasswordForm $forgotPasswordForm
     * @param ChangePasswordForm $changePasswordForm
     * @param SuspendUserForm $suspendUserForm
     */
    public function __construct(
        UserInterface $user,
        GroupInterface $group,
        RegisterForm $registerForm,
        UserForm $userForm,
        ResendActivationForm $resendActivationForm,
        ForgotPasswordForm $forgotPasswordForm,
        ChangePasswordForm $changePasswordForm,
        SuspendUserForm $suspendUserForm)
    {
        $this->user                 = $user;
        $this->group                = $group;
        $this->registerForm         = $registerForm;
        $this->userForm             = $userForm;
        $this->resendActivationForm = $resendActivationForm;
        $this->forgotPasswordForm   = $forgotPasswordForm;
        $this->changePasswordForm   = $changePasswordForm;
        $this->suspendUserForm      = $suspendUserForm;

        //Check CSRF token on POST
        $this->beforeFilter('csrf', ['on' => 'post']);

        // Set up Auth Filters
        $this->beforeFilter('auth', ['only' => ['change']]);
        $this->beforeFilter('inGroup:Admins', ['only' => ['show', 'index', 'destroy', 'suspend', 'unsuspend', 'ban', 'unban', 'edit', 'update']]);
//        ['except' => ['create', 'store', 'activate', 'resend', 'forgot', 'reset']]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = $this->user->all();

        return View::make('users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new user.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('users.create');
    }

    /**
     * Store a newly created user.
     *
     * @return Response
     */
    public function store()
    {
        // Form Processing
        $result = $this->registerForm->save(Input::all());

        if ($result['success']) {

            // Success!
            Session::flash('success', $result['message']);

            Stripe::customers()->create([
                'email' => $result['mailData']['email'],
            ]);

            Event::fire('user.signup', [
                'email'          => $result['mailData']['email'],
                'userId'         => $result['mailData']['userId'],
                'activationCode' => $result['mailData']['activationCode']
            ]);

            $customerIo = new CustomerIO([
                'id'    => $result['mailData']['userId'],
                'email' => $result['mailData']['email']
            ]);
            $customerIo->init();

            return Redirect::to('login#register');

        } else {
            Session::flash('error', $result['message']);

            return Redirect::to('login#register')
                ->withInput()
                ->withErrors($this->registerForm->errors());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $user = $this->user->byId($id);

        if ($user == null || !is_numeric($id)) {
            return \App::abort(404);
        }

        return View::make('users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $user = $this->user->byId($id);

        if ($user == null || !is_numeric($id)) {
            // @codeCoverageIgnoreStart
            return \App::abort(404);
            // @codeCoverageIgnoreEnd
        }

        $currentGroups = $user->getGroups()->toArray();
        $userGroups    = [];
        foreach ($currentGroups as $group) {
            array_push($userGroups, $group['name']);
        }
        $allGroups = $this->group->all();

        return View::make('users.edit')->with('user', $user)->with('userGroups', $userGroups)->with('allGroups', $allGroups);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        if (!is_numeric($id)) {
            // @codeCoverageIgnoreStart
            return \App::abort(404);
            // @codeCoverageIgnoreEnd
        }

        // Form Processing
        $result = $this->userForm->update(Input::all());

        if ($result['success']) {
            // Success!
            Session::flash('success', $result['message']);

            return Redirect::action('UserController@show', [$id]);

        } else {
            Session::flash('error', $result['message']);

            return Redirect::action('UserController@edit', [$id])
                ->withInput()
                ->withErrors($this->userForm->errors());
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        if (!is_numeric($id)) {
            // @codeCoverageIgnoreStart
            return \App::abort(404);
            // @codeCoverageIgnoreEnd
        }

        if ($this->user->destroy($id)) {
            Session::flash('success', 'User Deleted');

            return Redirect::to('/users');
        } else {
            Session::flash('error', 'Unable to Delete User');

            return Redirect::to('/users');
        }
    }

    /**
     * Activate a new user
     * @param $user
     * @param  string $code
     * @return Response
     * @internal param int $id
     */
    public function activate($user, $code)
    {
        if (!is_numeric($user->id)) {
            // @codeCoverageIgnoreStart
            return \App::abort(404);
            // @codeCoverageIgnoreEnd
        }

        $result = $this->user->activate($user->id, $code);

        if ($result['success']) {
            // Success!
            Session::flash('success', $result['message']);

            return Redirect::route('login');

        } else {
            Session::flash('error', $result['message']);

            return Redirect::route('login');
        }
    }

    /**
     * Process resend activation request
     * @return Response
     */
    public function resend()
    {
        // Form Processing
        $result = $this->resendActivationForm->resend(Input::all());

        if ($result['success']) {
            Event::fire('user.resend', [
                'email'          => $result['mailData']['email'],
                'userId'         => $result['mailData']['userId'],
                'activationCode' => $result['mailData']['activationCode']
            ]);

            // Success!
            Session::flash('success', $result['message']);

            return Redirect::route('home');
        } else {
            Session::flash('error', $result['message']);

            return Redirect::route('profile')
                ->withInput()
                ->withErrors($this->resendActivationForm->errors());
        }
    }

    /**
     * Process Forgot Password request
     * @return Response
     */
    public function forgot()
    {
        // Form Processing
        $result = $this->forgotPasswordForm->forgot(Input::all());

        if ($result['success']) {
            Event::fire('user.forgot', [
                'email'     => $result['mailData']['email'],
                'userId'    => $result['mailData']['userId'],
                'resetCode' => $result['mailData']['resetCode']
            ]);

            // Success!
            Session::flash('success', $result['message']);

            return Redirect::route('home');
        } else {
            Session::flash('error', $result['message']);

            return Redirect::route('forgotPasswordForm')
                ->withInput()
                ->withErrors($this->forgotPasswordForm->errors());
        }
    }

    /**
     * Process a password reset request link
     * @param $id
     * @param $code
     * @return \Illuminate\Http\RedirectResponse|void [type]       [description]
     * @internal param $ [type] $id   [description]
     * @internal param $ [type] $code [description]
     */
    public function reset($id, $code)
    {
        if (!is_numeric($id)) {
            // @codeCoverageIgnoreStart
            return \App::abort(404);
            // @codeCoverageIgnoreEnd
        }

        $result = $this->user->resetPassword($id, $code);

        if ($result['success']) {
            Event::fire('user.newpassword', [
                'email'       => $result['mailData']['email'],
                'newPassword' => $result['mailData']['newPassword']
            ]);

            // Success!
            Session::flash('success', $result['message']);

            return Redirect::route('home');

        } else {
            Session::flash('error', $result['message']);

            return Redirect::route('home');
        }
    }

    /**

app/controllers/users/UserDashboardController.php
<?php
use Gospel\Repo\User\UserRepoInterface;

class UserDashboardController extends \BaseController
{
    protected $user;

    /**
     * @param UserRepoInterface $user
     */
    public function __construct(UserRepoInterface $user)
    {
        $this->user = $user;
    }

    /**
     * User Dashboard
     * @return $this
     */
    public function index()
    {
        $user = $this->user->hasGetById(Sentry::getUser()->getId(), 'invites', ['invites']);
        if ($user) {
            return View::make('users.dashboard.index')
                ->with('user', $user);
        } else {
            $user = Sentry::getUser();

            return View::make('users.dashboard.index')
                ->with('user', $user);
        }
    }
}

app/controllers/users/UserFaqController.php
<?php
use Gospel\Repo\Faq\FaqInterface;
class UserFaqController extends \BaseController {
  /**
   * @var EloquentFaqRepository
   */
  protected $faq;

  public function __construct(FaqInterface $faq)
  {
    parent::__construct();
    $this->faq     = $faq;
  }
  /**
   * Display a listing of the resource.
   * GET /userfaq
   *
   * @return Response
   */
  public function index()
  {
    return View::make('users.faq.index')
      ->with('faqs', $this->faq->all())
      ->with('user', $this->user);
  }
}

app/views/admin/users/_partials/create_form.blade.php
<div class="row">
    <div class="col-xs-8">
        <div class="block">
            <div class="block-title">
                <h2><i class="fa fa-plus"></i> Add User</h2>
            </div>

            {{ Form::open(['route'=>'admin.users.store','role' => 'form' , 'class' => 'form-horizontal form-bordered']) }}

            <div class="form-group">
                {{ Form::label('first_name', 'First Name', [ 'class' => 'col-xs-3 control-label' ] ) }}
                <div class="col-xs-8">
                    {{ Form::text('first_name', null, ['class' => 'form-control', 'required' ,'placeholder' =>'Enter First Name..']) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('last_name', 'Last Name' , [ 'class' => 'col-xs-3 control-label' ]) }}
                <div class="col-xs-8">
                    {{ Form::text('last_name', null, ['class' => 'form-control', 'required' ,'placeholder' =>'Enter Last Name..']) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('email', 'Email' , [ 'class' => 'col-xs-3 control-label' ]) }}
                <div class="col-xs-8">
                    {{ Form::email('email', null, ['class' => 'form-control', 'required' , 'placeholder' =>'Enter Email ..']) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('password', 'Password' , [ 'class' => 'col-xs-3 control-label' ]) }}
                <div class="col-xs-8">
                    {{ Form::password('password', ['class' => 'form-control', 'required' ,'placeholder' =>'***********']) }}
                </div>
            </div>

            <div class="form-group">
                {{ Form::label('password_confirmation', 'Re-enter Password' , [ 'class' => 'col-xs-3 control-label' ]) }}
                <div class="col-xs-8">
                    {{ Form::password('password_confirmation', ['class' => 'form-control', 'required' , 'placeholder' =>'***********']) }}
                </div>
            </div>


            <!-- Role Form Input -->
            <div class="form-group">
                {{ Form::label('role', 'Role ', ['class' => 'col-md-3 control-label ']) }}
                <div class="col-xs-9 ">
                    {{ Form::select('role', $roles, null, ['class' => 'select-chosen form-control',  'style' => 'width:150px;']) }}
                </div>
            </div>


            <!-- Activated Form Input -->
            <div class="form-group">
                {{ Form::label('activated', 'Activated ?', ['class' => 'col-md-3 control-label ']) }}
                <div class="col-xs-9 ">
                    <label class="switch switch-primary">
                        {{ Form::checkbox('activated', true,false, ['id' => 'Activated']) }} <span></span>
                    </label>
                </div>
            </div>


            <div class="form-group form-actions">
                <div class="col-xs-8 col-xs-offset-3">
                    {{ HTML::link('admin/users', 'Cancel', ['class' => 'btn btn-sm btn-default'])}}
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Add User</button>
                </div>
            </div>

            {{ Form::close() }}

        </div>
    </div>
</div>

app/views/admin/users/_partials/edit_form.blade.php
<div class="col-xs-6">
    <div class="block">
        <div class="block-title">
            <h2><i class="fa fa-plus"></i> Edit User</h2>
        </div>

        {{ Form::model($user,['route'=>['admin.users.update' , $user->id],'method' => 'PATCH','role' => 'form' , 'class' => 'form-horizontal form-bordered']) }}

        <div class="form-group">
            {{ Form::label('first_name', 'First Name', [ 'class' => 'col-xs-3 control-label' ] ) }}
            <div class="col-xs-8">
                {{ Form::text('first_name', null, ['class' => 'form-control', 'required' ,'placeholder' =>'Enter First Name..']) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('last_name', 'Last Name' , [ 'class' => 'col-xs-3 control-label' ]) }}
            <div class="col-xs-8">
                {{ Form::text('last_name', null, ['class' => 'form-control', 'required' ,'placeholder' =>'Enter Last Name..']) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('email', 'Email' , [ 'class' => 'col-xs-3 control-label' ]) }}
            <div class="col-xs-8">
                {{ Form::email('email', null, ['class' => 'form-control', 'required' , 'placeholder' =>'Enter Email ..']) }}
            </div>
        </div>

        <!-- Role Form Input -->
        <div class="form-group">
            {{ Form::label('role', 'Role ', ['class' => 'col-md-3 control-label ']) }}
            <div class="col-xs-9 ">
                {{ Form::select('role', $roles, null, ['class' => 'select-chosen form-control',  'style' => 'width:150px;']) }}
            </div>
        </div>


        <!-- Activated Form Input -->
        <div class="form-group">
            {{ Form::label('activated', 'Activated ?', ['class' => 'col-md-3 control-label ']) }}
            <div class="col-xs-9 ">
                <label class="switch switch-primary">
                    {{ Form::checkbox('activated', true,false, ['id' => 'Activated']) }} <span></span>
                </label>
            </div>
        </div>


        <div class="form-group form-actions">
            <div class="col-xs-8 col-xs-offset-3">
                {{ HTML::link('admin/users', 'Cancel', ['class' => 'btn btn-sm btn-default'])}}
                <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Edit User</button>
            </div>
        </div>

        {{ Form::close() }}

    </div>
</div>

app/views/admin/users/_partials/password.blade.php
<div class="col-xs-6">
    <div class="block">
        <div class="block-title">
            <h2><i class="fa fa-group"></i> <strong>Change</strong> Password </h2>
        </div>

        {{ Form::open(['route'=>['admin.users.update' , $user->id],'method' => 'PATCH','role' => 'form' , 'class' => 'form-horizontal form-bordered']) }}

        <div class="form-group {{ $errors->has('newPassword') ? 'has-error' : '' }}">
            {{ Form::label('newPassword', 'New Password', ['class' => 'col-xs-3 control-label']) }}
            <div class="col-xs-9">
                {{ Form::password('newPassword', ['class' => 'form-control', 'placeholder' => ' Enter your new password' ]) }}
            </div>
        </div>

        <div class="form-group {{ $errors->has('newPassword_confirmation') ? 'has-error' : '' }}">
            {{ Form::label('newPassword_confirmation', 'Confirm Password', ['class' => 'col-xs-3 control-label']) }}
            <div class="col-xs-9">
                {{ Form::password('newPassword_confirmation', ['class' => 'form-control', 'placeholder' => 'Re-enter your new password']) }}
            </div>
        </div>
        <div class="form-group form-actions">
            <div class="col-xs-9 col-xs-offset-3">
                {{ Form::submit('Update Password', ['class' => 'btn btn-sm btn-primary'])}}
            </div>
        </div>

        {{ ($errors->has('newPassword') ?  '<br />' . $errors->first('newPassword') : '') }}
        {{ ($errors->has('newPassword_confirmation') ? '<br />' . $errors->first('newPassword_confirmation') : '') }}
        {{ Form::close() }}
    </div>
</div>

app/views/admin/users/_partials/quick_stats.blade.php
<div class="row text-center">
    <div class="col-sm-6 col-lg-3">
        <a href="{{URL::route('admin.users.create')}}" class="widget widget-hover-effect2">
            <div class="widget-extra themed-background-success">
                <h4 class="widget-content-light"><strong>Add New</strong> User</h4>
            </div>
            <div class="widget-extra-full"><span class="h2 text-success animation-expandOpen"><i class="fa fa-plus"></i></span></div>
        </a>
    </div>
    <div class="col-sm-6 col-lg-3">
        <a href="javascript:void(0)" class="widget widget-hover-effect2">
            <div class="widget-extra themed-background-danger">
                <h4 class="widget-content-light"><strong>All </strong> </h4>
            </div>
            <div class="widget-extra-full"><span class="h2 text-danger animation-expandOpen">71</span></div>
        </a>
    </div>
    <div class="col-sm-6 col-lg-3">
        <a href="javascript:void(0)" class="widget widget-hover-effect2">
            <div class="widget-extra themed-background-dark">
                <h4 class="widget-content-light"><strong>All </strong> </h4>
            </div>
            <div class="widget-extra-full"><span class="h2 themed-color-dark animation-expandOpen">20</span></div>
        </a>
    </div>
    <div class="col-sm-6 col-lg-3">
        <a href="javascript:void(0)" class="widget widget-hover-effect2">
            <div class="widget-extra themed-background-dark">
                <h4 class="widget-content-light"><strong>All</strong> </h4>
            </div>
            <div class="widget-extra-full"><span class="h2 themed-color-dark animation-expandOpen">91</span></div>
        </a>
    </div>
</div>

app/views/admin/users/_partials/users_table.blade.php
<div class="block full">
    <!-- All Products Title -->
    <div class="block-title">
        <div class="block-options pull-right">
            <a href="javascript:void(0)" class="btn btn-alt btn-sm btn-default" data-toggle="tooltip" title="Settings"><i class="fa fa-cog"></i></a>
        </div>
        <h2><strong>All</strong> Users</h2>
    </div>

    <!-- All Products Content -->
    <table id="ecom-products" class="table table-bordered table-striped table-vcenter">
        <thead>
        <tr>
            <th class="text-center">Email</th>
            <th class="text-center">First Name</th>
            <th class="text-center">Last Name</th>
            <th class="text-center">Group</th>
            <th class="text-center">Active</th>
            <th class="text-center">Created At</th>
            <th class="text-center">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($users as $eachUser)
        <tr>
            <td class="text-center"><a href="{{ route('admin.users.edit',$eachUser->id) }}" data-toggle="tooltip" title="Click to edit user" >{{ $eachUser->email }}</a></td>
            <td class="text-center">{{ $eachUser->first_name }}</td>
            <td class="text-center">{{ $eachUser->last_name }}</td>
            <td class="text-center">
                    <span class="label label-info">
                    @foreach($eachUser->getGroups() as $group)
                        {{ $group->name .", " }}
                        @endforeach
                    </span>
            </td>
            <td class="text-center">
                    @if($eachUser->activated ==1)
                    <span class="label label-success">
                    {{ "Active"}}
                    </span>
                    @else
                    <span class="label label-danger">
                    {{ " Not Active"}}
                    </span>
                    @endif

            </td>
            <td class="text-center">{{ $eachUser->created_at }}</td>
            <td class="text-center">
                <div class="btn-group btn-group-xs">
                    @if($eachUser->activated !=1)
                        <a href="{{ route('admin.users.activate',$eachUser->id) }}" data-toggle="tooltip" title="Activate Now" class="btn btn-xs btn-success"><i class="fa fa-user"></i></a>
                    @endif

                    <a href="{{ route('admin.users.edit', $eachUser->id) }}" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>
                    <a href="{{ route('admin.users.delete', $eachUser->id) }}" data-toggle="tooltip" title="Delete" class="btn btn-xs btn-danger btn-confirm"><i class="fa fa-times"></i></a>
                </div>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>